library(tidyverse)


# plots using MPG dataset
mpg

#Gráfico de dispersión: Crea un gráfico de dispersión que muestre la relación entre displ (desplazamiento del motor) y hwy (millas por galón en carretera).

ggplot(mpg, aes(displ, hwy)) +
geom_point() +
labs(x = "Engine Displacement in litres",
     y = "Miles per galon in Highway",
     title = "Dispersion between Displ and HWY")





#Boxplot: Crea un boxplot que compare la eficiencia de combustible en carretera (hwy) entre diferentes clases de autos (class).


ggplot(mpg, aes(reorder(class, hwy, median), hwy)) +
    geom_boxplot() +
    coord_flip() +
    labs(x = "Miles per galon in Highway",
            y = "Class of Car",
            title = "Efficiency between HWY and Classes of cars")





#Histograma: Realiza un histograma de la variable cty (millas por galón en ciudad).

ggplot(mpg, aes(cty, fill = class)) +
geom_histogram(bins=20)






#Gráfico de barras: Crea un gráfico de barras que muestre la cantidad de autos para cada tipo de transmisión (trans).


ggplot(mpg, aes(trans, fill = class)) +
geom_bar() +
coord_flip()


mpg %>% 
  group_by(trans) %>% 
  summarise(count = n())



#Facetas: Realiza un gráfico de dispersión de displ vs hwy con facetas por el tipo de tracción (drv).

ggplot(mpg, aes(displ, hwy)) +
geom_point() +
facet_wrap(~drv)



#Densidad: Crea un gráfico de densidad de hwy separado por el tipo de tracción (drv).

ggplot(mpg, aes(x = hwy,fill = drv)) +
geom_density(alpha = 0.5) +
labs(title = "Density of Highway MPG by Drive Type",
     x = "Highway MPG",
     fill = "Drive Type")





#Gráfico de línea: Crea un gráfico de línea que muestre cómo hwy varía con displ para cada fabricante (manufacturer).

ggplot(mpg, aes(hwy, displ)) +
geom_line() +
facet_wrap(~manufacturer)





#Gráfico de puntos con tamaños: Realiza un gráfico de dispersión de displ vs hwy, donde el tamaño de los puntos esté determinado por cyl (número de cilindros).

ggplot(mpg, aes(displ, hwy, size = cyl)) +
geom_point()



#Gráfico de mosaico: Crea un gráfico de mosaico para explorar la relación entre drv y class.


library(ggmosaic)


ggplot(mpg) +
  geom_mosaic(aes(x = product(drv), fill = class)) +
  labs(title = "Mosaic plot of drive type and car class",
       x = "Drive Type",
       y = "Count",
       fill = "Car Class")

#Gráfico de violín: Realiza un gráfico de violín para comparar la distribución de hwy entre diferentes fabricantes (manufacturer).

ggplot(mpg, aes(hwy, manufacturer)) +
geom_violin() 




#------------------------------------------------------------------------------
#------------------------------------------------------------------------------


#MTCARS

#Gráfico de dispersión: Realiza un gráfico de dispersión que muestre la relación entre wt (peso) y mpg (millas por galón).

ggplot(mtcars, aes(wt, mpg)) +
  geom_point()





#Boxplot: Crea un boxplot que compare la eficiencia de combustible (mpg) entre diferentes números de cilindros (cyl).

ggplot(mtcars, aes(reorder(cyl, mpg), mpg)) +
  geom_boxplot()



colnames(mtcars)

#Histograma: Realiza un histograma de la variable hp (caballos de fuerza).
ggplot(mtcars, aes(hp)) +
  geom_histogram(bins = 10)



#Gráfico de barras: Crea un gráfico de barras que muestre la cantidad de autos con diferentes números de marchas (gear).

ggplot(mtcars, aes(gear)) +
geom_bar()





#Facetas: Realiza un gráfico de dispersión de wt vs mpg con facetas por el número de cilindros (cyl).

ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  facet_wrap(~cyl)



#Densidad: Crea un gráfico de densidad de mpg separado por el número de marchas (gear).

tib <- as_tibble(mtcars)
tib$gear <- as_factor(tib$gear)


ggplot(tib, aes(x = mpg, fill = gear)) +
  geom_density(alpha=0.5)





#Gráfico de línea: Crea un gráfico de línea que muestre cómo mpg varía con wt para diferentes valores de cyl.

ggplot(mtcars, aes(mpg, wt)) +
geom_line() +
facet_wrap(~cyl)






#Gráfico de puntos con colores: Realiza un gráfico de dispersión de wt vs mpg, donde el color de los puntos esté determinado por gear.

ggplot(mtcars, aes(wt, mpg, color=gear)) +
  geom_point()





#Gráfico de mosaico: Crea un gráfico de mosaico para explorar la relación entre cyl y gear.

ggplot(mtcars) +
  geom_mosaic(aes(x = product(cyl), fill = factor(gear)))








#Gráfico de violín: Realiza un gráfico de violín para comparar la distribución de hp entre diferentes números de cilindros (cyl).

ggplot(mtcars, aes(x= factor(cyl), y = hp)) +
  geom_violin() +
  coord_flip()





