
library(tidyverse)
library(tidymodels)
library(nycflights13)
library(lubridate)



cancelled_flights <-   flights %>% 
  filter(is.na(arr_time))

good <- flights %>% 
  filter(!is.na(arr_time) & !is.na(air_time))
  
#------------------------------------------------------------------
#------------------------------------------------------------------

#separando columnas "sched_arr_time",  "dep_time" y las otras 

good <- good %>% 
  mutate(
          dep_hour = floor(dep_time / 100),
          dep_min = dep_time %% 100,
          arr_hour = floor(arr_time / 100),
          arr_min = arr_time %% 100,
          sched_arr_hour = floor(sched_arr_time / 100),
          sched_arr_min = sched_arr_time %% 100
)


# Uniendo columnas para tener una variable datetime 
good <- good %>% 
  mutate(
          sched_dep_date = ymd_hm(paste(year, month, day, hour, minute, sep = "-")),
          real_dep_date = ymd_hm(paste(year, month, day, dep_hour, dep_min, sep = "-")),
          sched_arr_date = ymd_hm(paste(year, month, day, sched_arr_hour, sched_arr_min, sep = "-")),
          real_arr_date = ymd_hm(paste(year, month, day, arr_hour, arr_min, sep = "-")))
  


# Eliminando columnas que no usare

good <- good %>% 
  select(sched_dep_date, 
         dep_delay, 
         real_dep_date, 
         sched_arr_date, 
         arr_delay, 
         real_arr_date, 
         carrier, 
         flight, 
         tailnum, 
         origin, 
         dest,             
         air_time, distance)



#--------------------------------------------------------------------------
#--------------------------------------------------------------------------

#weando con los quartiles para crear precios
#creando 6 categorias dependiendo del air_time
good <- good %>% 
  mutate(air_time_quartile = ntile(air_time, 6))

view(head(good))  


get_len <- function(df, col, cuartil){
    col <- enquo(col)
    len <- df %>% 
              filter(!!col == as.integer(cuartil)) %>% 
              nrow()
return(len)
}


len1 <- get_len(good, air_time_quartile, 1)
len2 <- get_len(good, air_time_quartile, 2)
len3 <- get_len(good, air_time_quartile, 3)
len4 <- get_len(good, air_time_quartile, 4)
len5 <- get_len(good, air_time_quartile, 5)
len6 <- get_len(good, air_time_quartile, 6)


set.seed(123)

precios_q1 <- round(runif(len1, min = 10, max= 30),2)
precios_q2 <- round(runif(len2, min = 40, max = 70),2)
precios_q3 <- round(runif(len3, min = 60, max = 100),2)
precios_q4 <- round(runif(len4, min = 130, max = 340),2)
precios_q5 <- round(runif(len5, min = 100, max = 470),2)
precios_q6 <- round(runif(len6, min = 250, max = 800),2)


good <- good %>% 
    mutate(precio = case_when(
    air_time_quartile == 1  ~ sample(precios_q1, n(), replace = TRUE),
    air_time_quartile == 2  ~ sample(precios_q2, n(), replace = TRUE),
    air_time_quartile == 3  ~ sample(precios_q3, n(), replace = TRUE),
    air_time_quartile == 4  ~ sample(precios_q4, n(), replace = TRUE),
    air_time_quartile == 5  ~ sample(precios_q5, n(), replace = TRUE),
    air_time_quartile == 6  ~ sample(precios_q6, n(), replace = TRUE),
))

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------



# separando por training y test
set.seed(123)
split <- initial_split(good, prop = 0.8)

trainData <- training(split)
testData <- testing(split)

#entrenar el modelo

library(parsnip)

model <- linear_reg() %>% 
          set_engine("lm") %>% 
          fit(distance~air_time, data = trainData)

# predicciones

predictions <- predict(model, new_data = testData)

results <- bind_cols(testData, predictions)

view(head(results))

metrics <- results %>% 
  metrics(truth = distance, estimate = .pred)

print(metrics)


#metrics manuales
r2 <- cor(results$distance, results$.pred)^2
print(r2)




RMSE <- sqrt(mean((results$distance - results$.pred)^2))
RMSE



#Visualizando

library(ggplot2)

ggplot(results, aes(x = distance, y = .pred))+
  geom_point() +
  geom_abline(slope = 1, intercept = 0, color = "red") +
  labs(x = "Actual distance", y = "Predicted distance", title = "Actual vs Predicted Distance")



